#ifndef DEFS_H
#define DEFS_H

#define	DEBUG 0
#define PLAYER_AUDIO_BUFFER_SIZE 1024
#define PLAYER_USE_AUDIO_CALLBACK 1
#define PLAYER_PKTQ_MAX_LEN 20
#define PLAYER_VIDEOQ_FRMS_MAX_LEN 10
#define PLAYER_AUDIOQ_FRMS_MAX_LEN 15
#define PLAYER_FONT "assets/ubuntu.ttf"

#endif // DEFS_H