#ifndef DEFS_H
#define DEFS_H

#define	DEBUG 0
#define SDL_AUDIO_BUFFER_SIZE 1024
#define PLAYER_VIDEOQ_PKTS_MAX_LEN 15
#define PLAYER_VIDEOQ_FRMS_MAX_LEN 15
#define PLAYER_AUDIOQ_FRMS_MAX_LEN 20
#define AVCODEC_MAX_AUDIO_FRAME_SIZE 192000

#endif // DEFS_H